development:
  adapter: mysql2
  database: felicalc
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  database: felicalc_test 
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  database: felicalc
  username: root
  password: root
  host: localhost


