development:
  adapter: mysql2
  database: flextures_dev
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  database: flextures_test 
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  database: flextures
  username: root
  password: root
  host: localhost


