development:
  adapter: mysql2
  database: jp_fullstack_development
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  database: jP_fullstack_test 
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  database: jp_fullstack
  username: cook24
  password: root
  host: localhost


